# backend/Dockerfile.mqtt

FROM python:3.11-slim

WORKDIR /app
COPY mqtt_logger.py mqtt_logger.py
COPY requirements.txt requirements.txt

RUN pip install --no-cache-dir -r requirements.txt

CMD ["python", "mqtt_logger.py"]
